name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        tags: pzwd/foodgram_frontend:latest
        push: true

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        tags: pzwd/foodgram_backend:latest
        push: true
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        scp docker-compose.yml $USER@$HOST:/path/to/project/
        ssh $USER@$HOST "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}; \
                         cd /path/to/project; \
                         docker-compose pull frontend backend; \
                         docker-compose down; \
                         docker-compose up --build -d;"